---
name: Test
on:
  push:
    branches:
      - '*'

jobs:

  action-test:
    runs-on: ubuntu-latest
    name: Testing Ansible
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Perform ansible playbook - Debug Tasks - Skiping tags
        uses: ./
        with:
          playbook: ./test/playbook.yml
          inventory: ./test/inventory
          verbosity: v
          skipTags: 'apache'
          tags: 'custom'

      - name: Perform ansible playbook - Install Apache - Using tag
        uses: ./ #isweluiz/ansible-in-docker-action@main
        with:
          playbook: ./test/playbook.yml
          inventory: ./test/inventory
          verbosity: vv
          tags: 'apache,output'

      - name: Perform ansible playbook - Extra variable - Using tag
        uses: ./ #isweluiz/ansible-in-docker-action@main
        with:
          playbook: ./test/playbook.yml
          inventory: ./test/inventory
          verbosity: vv
          skipTags: 'apache,output,custom'
          extraVars: '"variable_xpto=Ansible"'
