# ================================================================================== #
#   Trigger
#   - On each new pull_request
# ================================================================================== #
---
name: CI - PR title check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: PR title check
    steps:
      - id: pr-title-check   
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16
        with:
          regex: '^RELEASE-\d+'
